export { default as Home } from './Home';
export { default as About } from './About';
export { default as Resources } from './Resources';
export { default as Features } from './Features';
export { default as Contact } from './Contact';
export { default as Login } from './Login';
export { default as SignUpPage } from './Signup';
export { default as Reset } from './Reset';
export { default as UserManagementPage } from './UserManagementPage';
